pipeline:
  name: db-argo-demo
  identifier: dbargodemo
  projectIdentifier: AkashSandbox
  orgIdentifier: sandbox
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Akash_Docker_Hub
                    repo: eks-config-ui
                    tags:
                      - staging-001
                    caching: true
                    dockerfile: ./Dockerfile
                    context: .
  properties:
    ci:
      codebase:
        connectorRef: akashHarnessGitHub
        repoName: db-argo-demo
        build: <+input>
